#run-OdsActionLogOt2DwdActionDoLog.job
type=command
command=sh spark-submit \
 --master yarn \
 --deploy-mode cluster \
 --num-executors 40 \
 --executor-memory 3G \
 --driver-memory 1G \
 --executor-cores 2 \
 --conf spark.yarn.maxAppAttempts=0 \
 --queue default \
 --class com.pep.dwd.OdsActionLogOt2DwdActionDoLog \
 /root/pep-job/yunwang-dw-1.0-SNAPSHOT.jar 1
working.dir=/usr/local/azkaban/azkaban_work_dir/working_dir