#run-DwdResourceDetailWidth2AdsResourceSummary.job
type=command
command=sh spark-submit \
 --master yarn \
 --deploy-mode cluster \
 --num-executors 40 \
 --executor-memory 3G \
 --driver-memory 1G \
 --executor-cores 2 \
 --queue dwq \
 --conf spark.yarn.maxAppAttempts=0 \
 --class com.pep.ads.resource.DwdResourceDetailWidth2AdsResourceSummary \
 /root/pep-job/yunwang-dw-1.0-SNAPSHOT.jar
dependencies=run-OdsJxwResource2DwdResourceJxw
working.dir=/usr/local/azkaban/azkaban_work_dir/working_dir