#run-DwsUvTotal2DwdUserArea.job
type=command
command=sh spark-submit \
 --master yarn \
 --deploy-mode cluster \
 --num-executors 20 \
 --executor-memory 3G \
 --driver-memory 1G \
 --executor-cores 2 \
 --queue default \
 --conf spark.yarn.maxAppAttempts=0 \
 --class com.pep.dwd.DwsUvTotal2DwdUserArea \
 /root/pep-job/yunwang-dw-1.0-SNAPSHOT.jar
dependencies=run-DwdActionDoLog2DwsUv
working.dir=/usr/local/azkaban/azkaban_work_dir/working_dir